# Generated by Django 5.1 on 2024-08-25 20:29

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KategoriModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=30)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="isim", unique=True
                    ),
                ),
            ],
            options={
                "db_table": "kategori",
            },
        ),
    ]
