# Generated by Django 5.1 on 2024-08-30 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kategorimodels",
            options={"verbose_name": "Kategori", "verbose_name_plural": "Kategoriler"},
        ),
    ]
