# Generated by Django 5.1 on 2024-08-30 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_yazilarmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="yazilarmodel",
            options={"verbose_name": "Yazi", "verbose_name_plural": "Yazilar"},
        ),
        migrations.AlterModelTable(
            name="yazilarmodel",
            table="Yazi",
        ),
    ]
