# Generated by Django 5.1 on 2024-08-30 12:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_yazilarmodel_options_alter_yazilarmodel_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yazilarmodel",
            name="icerik",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
