# Generated by Django 5.1 on 2024-08-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_yorummodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="IletisimModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=250)),
                ("isim_soyisim", models.CharField(max_length=150)),
                ("mesaj", models.TextField()),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Iletisim",
                "verbose_name_plural": "Iletisim",
                "db_table": "iletisim",
            },
        ),
    ]
