# Generated by Django 5.1 on 2024-08-31 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_iletisimmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yorummodel",
            old_name="guncellenme_tarihi",
            new_name="duzenleme_tarihi",
        ),
    ]
